### ISSUE TITLE
😖莎莎，栗子在哪里

### ISSUE THREAD

**Issue by sg-first** [MarisaKirisame/first_order_logic_prover#41]
😖想试用一下，然而找不到栗子（其实要有个文档更好了，感兴趣的人嘛

**Comment by MarisaKirisame** [comment]
https://github.com/MarisaKirisame/first_order_logic_prover/blob/master/test.hpp
编译用clang，多给点内存，不然会爆。。。

**Comment by sg-first** [comment]
😖谢谢
